services:
  - type: web
    name: kuska-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        value: https://kuska-server.onrender.com
      - key: NODE_VERSION
        value: 18
